COMPONENT=AutoConfigAppC
# BUILD_EXTRA_DEPS=AutoConfigMsg.class

# AutoConfigMsg.class: AutoConfigMsg.java
# 	javac AutoConfigMsg.java

# AutoConfigMsg.java:
# 	mig java -target=null  -java-classname=AutoConfigMsg AutoConfig.h AutoConfigMsg -o $@

include $(MAKERULES)