#
# This class is automatically generated by mig. DO NOT EDIT THIS FILE.
# This class implements a Python interface to the 'RadioCountMsg'
# message type.
#

import tinyos.message.Message

# The default size of this message type in bytes.
DEFAULT_MESSAGE_SIZE = 28

# The Active Message type associated with this message.
AM_TYPE = 6

class RadioCountMsg(tinyos.message.Message.Message):
    # Create a new RadioCountMsg of size 28.
    def __init__(self, data="", addr=None, gid=None, base_offset=0, data_length=28):
        tinyos.message.Message.Message.__init__(self, data, addr, gid, base_offset, data_length)
        self.amTypeSet(AM_TYPE)
    
    # Get AM_TYPE
    def get_amType(cls):
        return AM_TYPE
    
    get_amType = classmethod(get_amType)
    
    #
    # Return a String representation of this message. Includes the
    # message type name and the non-indexed field values.
    #
    def __str__(self):
        s = "Message <RadioCountMsg> \n"
        try:
            s += "  [messageType=0x%x]\n" % (self.get_messageType())
        except:
            pass
        try:
            s += "  [nodeId=0x%x]\n" % (self.get_nodeId())
        except:
            pass
        try:
            s += "  [counter=0x%x]\n" % (self.get_counter())
        except:
            pass
        try:
            s += "  [payloadsize=0x%x]\n" % (self.get_payloadsize())
        except:
            pass
        try:
            s += "  [buffer=";
            for i in range(0, 21):
                s += "0x%x " % (self.getElement_buffer(i) & 0xff)
            s += "]\n";
        except:
            pass
        return s

    # Message-type-specific access methods appear below.

    #
    # Accessor methods for field: messageType
    #   Field type: short
    #   Offset (bits): 0
    #   Size (bits): 8
    #

    #
    # Return whether the field 'messageType' is signed (False).
    #
    def isSigned_messageType(self):
        return False
    
    #
    # Return whether the field 'messageType' is an array (False).
    #
    def isArray_messageType(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'messageType'
    #
    def offset_messageType(self):
        return (0 / 8)
    
    #
    # Return the offset (in bits) of the field 'messageType'
    #
    def offsetBits_messageType(self):
        return 0
    
    #
    # Return the value (as a short) of the field 'messageType'
    #
    def get_messageType(self):
        return self.getUIntElement(self.offsetBits_messageType(), 8, 1)
    
    #
    # Set the value of the field 'messageType'
    #
    def set_messageType(self, value):
        self.setUIntElement(self.offsetBits_messageType(), 8, value, 1)
    
    #
    # Return the size, in bytes, of the field 'messageType'
    #
    def size_messageType(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of the field 'messageType'
    #
    def sizeBits_messageType(self):
        return 8
    
    #
    # Accessor methods for field: nodeId
    #   Field type: int
    #   Offset (bits): 8
    #   Size (bits): 16
    #

    #
    # Return whether the field 'nodeId' is signed (False).
    #
    def isSigned_nodeId(self):
        return False
    
    #
    # Return whether the field 'nodeId' is an array (False).
    #
    def isArray_nodeId(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'nodeId'
    #
    def offset_nodeId(self):
        return (8 / 8)
    
    #
    # Return the offset (in bits) of the field 'nodeId'
    #
    def offsetBits_nodeId(self):
        return 8
    
    #
    # Return the value (as a int) of the field 'nodeId'
    #
    def get_nodeId(self):
        return self.getUIntElement(self.offsetBits_nodeId(), 16, 1)
    
    #
    # Set the value of the field 'nodeId'
    #
    def set_nodeId(self, value):
        self.setUIntElement(self.offsetBits_nodeId(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'nodeId'
    #
    def size_nodeId(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'nodeId'
    #
    def sizeBits_nodeId(self):
        return 16
    
    #
    # Accessor methods for field: counter
    #   Field type: int
    #   Offset (bits): 24
    #   Size (bits): 16
    #

    #
    # Return whether the field 'counter' is signed (False).
    #
    def isSigned_counter(self):
        return False
    
    #
    # Return whether the field 'counter' is an array (False).
    #
    def isArray_counter(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'counter'
    #
    def offset_counter(self):
        return (24 / 8)
    
    #
    # Return the offset (in bits) of the field 'counter'
    #
    def offsetBits_counter(self):
        return 24
    
    #
    # Return the value (as a int) of the field 'counter'
    #
    def get_counter(self):
        return self.getUIntElement(self.offsetBits_counter(), 16, 1)
    
    #
    # Set the value of the field 'counter'
    #
    def set_counter(self, value):
        self.setUIntElement(self.offsetBits_counter(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'counter'
    #
    def size_counter(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'counter'
    #
    def sizeBits_counter(self):
        return 16
    
    #
    # Accessor methods for field: payloadsize
    #   Field type: int
    #   Offset (bits): 40
    #   Size (bits): 16
    #

    #
    # Return whether the field 'payloadsize' is signed (False).
    #
    def isSigned_payloadsize(self):
        return False
    
    #
    # Return whether the field 'payloadsize' is an array (False).
    #
    def isArray_payloadsize(self):
        return False
    
    #
    # Return the offset (in bytes) of the field 'payloadsize'
    #
    def offset_payloadsize(self):
        return (40 / 8)
    
    #
    # Return the offset (in bits) of the field 'payloadsize'
    #
    def offsetBits_payloadsize(self):
        return 40
    
    #
    # Return the value (as a int) of the field 'payloadsize'
    #
    def get_payloadsize(self):
        return self.getUIntElement(self.offsetBits_payloadsize(), 16, 1)
    
    #
    # Set the value of the field 'payloadsize'
    #
    def set_payloadsize(self, value):
        self.setUIntElement(self.offsetBits_payloadsize(), 16, value, 1)
    
    #
    # Return the size, in bytes, of the field 'payloadsize'
    #
    def size_payloadsize(self):
        return (16 / 8)
    
    #
    # Return the size, in bits, of the field 'payloadsize'
    #
    def sizeBits_payloadsize(self):
        return 16
    
    #
    # Accessor methods for field: buffer
    #   Field type: short[]
    #   Offset (bits): 56
    #   Size of each element (bits): 8
    #

    #
    # Return whether the field 'buffer' is signed (False).
    #
    def isSigned_buffer(self):
        return False
    
    #
    # Return whether the field 'buffer' is an array (True).
    #
    def isArray_buffer(self):
        return True
    
    #
    # Return the offset (in bytes) of the field 'buffer'
    #
    def offset_buffer(self, index1):
        offset = 56
        if index1 < 0 or index1 >= 21:
            raise IndexError
        offset += 0 + index1 * 8
        return (offset / 8)
    
    #
    # Return the offset (in bits) of the field 'buffer'
    #
    def offsetBits_buffer(self, index1):
        offset = 56
        if index1 < 0 or index1 >= 21:
            raise IndexError
        offset += 0 + index1 * 8
        return offset
    
    #
    # Return the entire array 'buffer' as a short[]
    #
    def get_buffer(self):
        tmp = [None]*21
        for index0 in range (0, self.numElements_buffer(0)):
                tmp[index0] = self.getElement_buffer(index0)
        return tmp
    
    #
    # Set the contents of the array 'buffer' from the given short[]
    #
    def set_buffer(self, value):
        for index0 in range(0, len(value)):
            self.setElement_buffer(index0, value[index0])

    #
    # Return an element (as a short) of the array 'buffer'
    #
    def getElement_buffer(self, index1):
        return self.getUIntElement(self.offsetBits_buffer(index1), 8, 1)
    
    #
    # Set an element of the array 'buffer'
    #
    def setElement_buffer(self, index1, value):
        self.setUIntElement(self.offsetBits_buffer(index1), 8, value, 1)
    
    #
    # Return the total size, in bytes, of the array 'buffer'
    #
    def totalSize_buffer(self):
        return (168 / 8)
    
    #
    # Return the total size, in bits, of the array 'buffer'
    #
    def totalSizeBits_buffer(self):
        return 168
    
    #
    # Return the size, in bytes, of each element of the array 'buffer'
    #
    def elementSize_buffer(self):
        return (8 / 8)
    
    #
    # Return the size, in bits, of each element of the array 'buffer'
    #
    def elementSizeBits_buffer(self):
        return 8
    
    #
    # Return the number of dimensions in the array 'buffer'
    #
    def numDimensions_buffer(self):
        return 1
    
    #
    # Return the number of elements in the array 'buffer'
    #
    def numElements_buffer():
        return 21
    
    #
    # Return the number of elements in the array 'buffer'
    # for the given dimension.
    #
    def numElements_buffer(self, dimension):
        array_dims = [ 21,  ]
        if dimension < 0 or dimension >= 1:
            raise IndexException
        if array_dims[dimension] == 0:
            raise IndexError
        return array_dims[dimension]
    
    #
    # Fill in the array 'buffer' with a String
    #
    def setString_buffer(self, s):
         l = len(s)
         for i in range(0, l):
             self.setElement_buffer(i, ord(s[i]));
         self.setElement_buffer(l, 0) #null terminate
    
    #
    # Read the array 'buffer' as a String
    #
    def getString_buffer(self):
        carr = "";
        for i in range(0, 4000):
            if self.getElement_buffer(i) == chr(0):
                break
            carr += self.getElement_buffer(i)
        return carr
    
